version: '3.8'

services:
  # api:
  

  postgres-rivella:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rivella
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./Rivella.BackEnd/sql/init.sql:/docker-entrypoint-initdb.d/init.sql